eureka:
   client:
      registerWithEureka: true
      fetchRegistry: true
      serviceUrl:
       defalutZone: http://localhost:8761/eureka
   instance:
      hostname: localhost
microservic:
  payment-service:
    endpoints:
      endpoint:
        uri: http://PAYMENT-SERVICE/payment/doPayment
     
  payment-service:
    endpoints:
      endpoint:
        uri: http://ORDER-SERVICE/order/bookOrder
